Remove failing `ecosystem-cert-preflight-checks`
which is not used to work with containers without architecture
(and there's no way to force architecture via parameters).

From logs:

```
step-check-container
time="2024-12-12T08:09:55Z" level=info msg="certification library version" version="1.10.2 <commit: 3a93f15cba1f3a4517c02f10914d6cff5cfa5c60>"
Error: cannot process image manifest of different arch without platform override
Usage:
  preflight check container [flags]
...
```