Delete `deprecated-base-image-check` task
because there's no base image anyway and because the task isn't happy
due to architecture not being specified on the image.

```
step-check-images
WARNING: SBOM attachments are deprecated and support will be removed in a Cosign release soon after 2024-02-22 (see https://github.com/sigstore/cosign/issues/2755). Instead, please use SBOM attestations.
WARNING: Downloading SBOMs this way does not ensure its authenticity. If you want to ensure a tamper-proof SBOM, download it using 'cosign download attestation <image uri>'.
Error: could not parse reference: quay.io/redhat-user-workloads/rh-acs-tenant/acs-konflux-tasks@
main.go:74: error during command execution: could not parse reference: quay.io/redhat-user-workloads/rh-acs-tenant/acs-konflux-tasks@
{"result":"ERROR","timestamp":"2024-12-11T19:23:19+00:00","note":"Unexpected error: Script errored at command: cosign download sbom $arch_imageanddigest > ${SBOM_FILE_PATH}.","namespace":"default","successes":0,"failures":0,"warnings":0}
```